### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by Trivoz** [Trivoz/sourcerer#1]
this isnt what issues are for but idc. this is just something to mark off as i get stuff done.
I don't think that each task deserves its own thing because that's:
a. a lot of work
and b. too much considering the size of each task is quite small

# tasks (generic)
 - [ ] serialize and deserialize configuration

## paser
 - [ ] tasks should be able to be indexed by their ID
 - [ ] the `--parser` flag should be able to point to any given file that is a json file. (there should be error handling for when
       the pointed file cannot be deserialized.
